name = "authc1-do"
compatibility_date = "2022-12-13"
main="src/index.ts"
usage_model = "bundled"

kv_namespaces = [
  { binding = "AUTHC1_USER_DETAILS", preview_id = "97156442adbc449a9502ff633e06f905", id = "97156442adbc449a9502ff633e06f905" },
  { binding = "AUTHC1_APPLICATION_PROVIDER_DETAILS", preview_id = "4ca6c6de25c040649f04736c6381b043", id = "4ca6c6de25c040649f04736c6381b043" }
]

[durable_objects]
bindings = [
	{ name = "AuthC1App", class_name = "AuthC1App" },
    { name = "AuthC1Token", class_name = "AuthC1Token" },
    { name = "AuthC1User", class_name = "AuthC1User" },
    { name = "AuthC1Activity", class_name = "AuthC1Activity" }
]

[[queues.producers]]
queue = "authc1-do-activity-queue"
binding = "AUTHC1_ACTIVITY_QUEUE"

[[queues.consumers]]
queue = "authc1-do-activity-queue"
max_batch_size = 1
max_batch_timeout = 5

[[migrations]]
tag = "v1"
new_classes = ["AuthC1App", "AuthC1Token", "AuthC1User", "AuthC1Activity"]